### ISSUE TITLE
fix: Bacalhau roadmap yields internal server error

### ISSUE THREAD

**Issue by juliaxbow** [pln-planning-tools/StarMaps#158]
**Error description:** 
- Searching for the Bacalhau roadmap in starmaps results in internal server error (https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/1151).
<img width="567" alt="Screen Shot 2022-11-21 at 11 13 24 AM" src="https://user-images.githubusercontent.com/58958327/203139863-bece3985-defd-44ae-a621-4cbc89fe4795.png">

**Addt'l Context:** 
- This error was discovered in chrome, safari, and brave
- All issues were rendering correctly in GitHub as recently as 3pm PT Sunday, Nov 20.  Issue maintainer first noticed the bug the evening of Sunday, Nov 20

**Fix**
- Not sure. Some Bacalhau child milestones yield the same error (e.g. https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/1220) while others don't (e.g. https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/1226). These two issues are structured exactly the same and carry the same label assignments, so I can't discern the cause

**Comment by SgtPooki** [comment]
I believe this is related to #157

**Comment by juliaxbow** [comment]
I wondered so, too, but did notice this happening before issue #157 became a problem for me

**Comment by SgtPooki** [comment]
Ok.. yea.. we need a better way to debug these errors.

**Comment by SgtPooki** [comment]
errors from vercel show:

```bash
[GET] /api/roadmap?owner=filecoin-project&repo=bacalhau&issue_number=1151&filter_group=undefined
17:05:40:35
info  - Loaded env from /var/task/.env.production
API hit: roadmap {
  repo: 'bacalhau',
  issue_number: '1151',
  filter_group: 'undefined',
  owner: 'filecoin-project'
}
2022-11-22T01:05:47.105Z	84953bff-dc86-4e36-8882-2a518f501e96	ERROR	error: Error: Unsupported URL
    at paramsFromUrl (/var/task/.next/server/pages/api/roadmap.js:380:15)
    at /var/task/.next/server/pages/api/roadmap.js:493:101
    at Array.map (<anonymous>)
    at resolveChildren (/var/task/.next/server/pages/api/roadmap.js:492:33)
    at /var/task/.next/server/pages/api/roadmap.js:508:44
    at Array.map (<anonymous>)
    at resolveChildrenWithDepth (/var/task/.next/server/pages/api/roadmap.js:506:41)
    at async /var/task/.next/server/pages/api/roadmap.js:512:27
    at async Promise.all (index 1)
    at async resolveChildrenWithDepth (/var/task/.next/server/pages/api/roadmap.js:506:16)
2022-11-22T01:05:51.931Z	84953bff-dc86-4e36-8882-2a518f501e96	WARN	API response for /api/roadmap?repo=bacalhau&issue_number=1151&filter_group=undefined&owner=filecoin-project exceeds 4MB. API Routes are meant to respond quickly. https://nextjs.org/docs/messages/api-routes-response-size-limit
[ERROR] [1669079152726] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.
[GET] /roadmap/github.com/filecoin-project/bacalhau/issues/1151
17:05:38:59
2022-11-22T01:05:52.813Z	56c127f6-e5ee-43e8-9bb0-805142a81b88	ERROR	FetchError: invalid json response body at https://starmaps-53a2zomc1-ipfs-ignite.vercel.app/api/roadmap?owner=filecoin-project&repo=bacalhau&issue_number=1151&filter_group=undefined reason: Unexpected token < in JSON at position 0
    at /var/task/node_modules/next/dist/compiled/node-fetch/index.js:1:51220
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getServerSideProps (/var/task/.next/server/pages/roadmap/[...slug].js:1828:22)
    at async Object.renderToHTML (/var/task/node_modules/next/dist/server/render.js:508:20)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:687:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/var/task/node_modules/next/dist/server/base-server.js:796:28)
    at async /var/task/node_modules/next/dist/server/response-cache/index.js:80:36 {
  type: 'invalid-json',
  page: '/roadmap/[...slug]'
}
RequestId: 56c127f6-e5ee-43e8-9bb0-805142a81b88 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by SgtPooki** [comment]
I think this might be solved by #164 because they have a child item listed that includes a comment, such as `https://github.com/ipfs/kubo/issues/6523#issuecomment-547254760`

**Comment by SgtPooki** [comment]
yep. locally: 

```bash
error: Error: Error resolving children: Error: Unsupported URL: https://github.com/ipfs/kubo/issues/6523#issuecomment-547254760
    at eval (webpack-internal:///(api)/./pages/api/roadmap.ts:34:15)
    at async eval (webpack-internal:///(api)/./pages/api/roadmap.ts:42:38)
    at async Promise.all (index 2)
    at async resolveChildrenWithDepth (webpack-internal:///(api)/./pages/api/roadmap.ts:40:16)
    at async eval (webpack-internal:///(api)/./pages/api/roadmap.ts:46:27)
    at async Promise.all (index 1)
    at async resolveChildrenWithDepth (webpack-internal:///(api)/./pages/api/roadmap.ts:40:16)
    at async handler (webpack-internal:///(api)/./pages/api/roadmap.ts:112:28)
    at async Object.apiResolver (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async DevServer.runApi (/Users/sgtpooki/code/work/protocol.ai/pln-planning-tools/Starmaps/node_modules/next/dist/server/next-server.js:481:9)
```

**Comment by SgtPooki** [comment]
https://www.starmaps.app/roadmap/github.com/filecoin-project/bacalhau/issues/1151 now shows the reason for the error, though it's not super helpful: `invalid json response body at https://starmaps-7q8n61y02-ipfs-ignite.vercel.app/api/roadmap?owner=filecoin-project&repo=bacalhau&issue_number=1151&filter_group=undefined reason: Unexpected token < in JSON at position 0`

**Comment by SgtPooki** [comment]
Ok, after diving through this time and time again, I believe what we're running into is a server function timeout of 10seconds. See https://vercel.com/docs/concepts/limits/overview#general-limits

we're on the "pro" plan, but it seems to be timing out after 15 seconds:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/1173416/203237856-1324f9b9-a8b0-48c0-9be4-68f25be243b7.png">

It's taking the server up to 15 seconds just to return a response.. which leads us to #103 which is a significant ask for MVP.

We are not running into this issue locally, which lead me to check vercel, and apparently we can't adjust those timeouts without paying more money. (@whizzzkid time to look at droplets or other solutions.... but making the app more performant can't hurt)

Local timings: 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/1173416/203238338-4f1cf5f6-bfd9-4743-bf12-3e8a39a08d3d.png">


I have some ideas on how to solve this quick and dirty but I'm going to need to come at this tomorrow with a fresh head to get things resolved for MVP.

**Comment by SgtPooki** [comment]
> Is there a way to partially render the roadmap and log that error (in more user friendly terms, ideally) in the error log? I assume that's what you're working towards, vs further restricting the parameters and requiring an update to the user guidelines, but lmk 🙇

@juliaxbow Yea, that's what we're doing already, and I thought we had a bug with that, but I confirmed and improved and confirmed again, and it's definitely that 1151 is just a monster of a roadmap and vercel is limiting us. See my previous comment

**Comment by SgtPooki** [comment]
Opened up https://github.com/pln-planning-tools/StarMaps/pull/179 which addresses some of the concerns with the slow loading and large response.
